version: '3.3'
services:
  app:
    build: .
    container_name: sample-django-circleci
    platform: linux/amd64
    image: sample-django-circleci
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8020:8000