version: 2.1
jobs:
  build_test:
    docker:
      - image: cimg/python:3.10.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r etc/base.txt

  build_docker:
    docker:
      - image: cimg/python:3.10.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: |
            docker build -t priyapahwa19/sample-django-circleci:latest .
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push priyapahwa19/sample-django-circleci:latest

workflows:
  build-workflow:
    jobs:
      - build_test:
          filters:
            branches:
              only:
                - main
      - build_docker:
          requires:
            - build_test
          filters:
            branches:
              only:
                - main